#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Base_Datos
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Tienda_Musica")]
	public partial class Base_AzureDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void Insertalbum_venta(album_venta instance);
    partial void Updatealbum_venta(album_venta instance);
    partial void Deletealbum_venta(album_venta instance);
    partial void Insertartista(artista instance);
    partial void Updateartista(artista instance);
    partial void Deleteartista(artista instance);
    partial void Insertartista_cancion(artista_cancion instance);
    partial void Updateartista_cancion(artista_cancion instance);
    partial void Deleteartista_cancion(artista_cancion instance);
    partial void Insertcancion(cancion instance);
    partial void Updatecancion(cancion instance);
    partial void Deletecancion(cancion instance);
    partial void Insertcancion_album(cancion_album instance);
    partial void Updatecancion_album(cancion_album instance);
    partial void Deletecancion_album(cancion_album instance);
    partial void Insertdisquera(disquera instance);
    partial void Updatedisquera(disquera instance);
    partial void Deletedisquera(disquera instance);
    partial void Insertfactura(factura instance);
    partial void Updatefactura(factura instance);
    partial void Deletefactura(factura instance);
    partial void Insertgenero_musical(genero_musical instance);
    partial void Updategenero_musical(genero_musical instance);
    partial void Deletegenero_musical(genero_musical instance);
    partial void Insertitem_factura(item_factura instance);
    partial void Updateitem_factura(item_factura instance);
    partial void Deleteitem_factura(item_factura instance);
    partial void Insertpersona(persona instance);
    partial void Updatepersona(persona instance);
    partial void Deletepersona(persona instance);
    partial void Insertrol(rol instance);
    partial void Updaterol(rol instance);
    partial void Deleterol(rol instance);
    partial void Inserttienda(tienda instance);
    partial void Updatetienda(tienda instance);
    partial void Deletetienda(tienda instance);
    partial void Insertusuario(usuario instance);
    partial void Updateusuario(usuario instance);
    partial void Deleteusuario(usuario instance);
    partial void Insertcompras(compras instance);
    partial void Updatecompras(compras instance);
    partial void Deletecompras(compras instance);
    #endregion
		
		public Base_AzureDataContext() : 
				base(global::Base_Datos.Properties.Settings.Default.Tienda_MusicaConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public Base_AzureDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Base_AzureDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Base_AzureDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Base_AzureDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<album_venta> album_venta
		{
			get
			{
				return this.GetTable<album_venta>();
			}
		}
		
		public System.Data.Linq.Table<artista> artista
		{
			get
			{
				return this.GetTable<artista>();
			}
		}
		
		public System.Data.Linq.Table<artista_cancion> artista_cancion
		{
			get
			{
				return this.GetTable<artista_cancion>();
			}
		}
		
		public System.Data.Linq.Table<cancion> cancion
		{
			get
			{
				return this.GetTable<cancion>();
			}
		}
		
		public System.Data.Linq.Table<cancion_album> cancion_album
		{
			get
			{
				return this.GetTable<cancion_album>();
			}
		}
		
		public System.Data.Linq.Table<disquera> disquera
		{
			get
			{
				return this.GetTable<disquera>();
			}
		}
		
		public System.Data.Linq.Table<factura> factura
		{
			get
			{
				return this.GetTable<factura>();
			}
		}
		
		public System.Data.Linq.Table<genero_musical> genero_musical
		{
			get
			{
				return this.GetTable<genero_musical>();
			}
		}
		
		public System.Data.Linq.Table<item_factura> item_factura
		{
			get
			{
				return this.GetTable<item_factura>();
			}
		}
		
		public System.Data.Linq.Table<persona> persona
		{
			get
			{
				return this.GetTable<persona>();
			}
		}
		
		public System.Data.Linq.Table<rol> rol
		{
			get
			{
				return this.GetTable<rol>();
			}
		}
		
		public System.Data.Linq.Table<tienda> tienda
		{
			get
			{
				return this.GetTable<tienda>();
			}
		}
		
		public System.Data.Linq.Table<usuario> usuario
		{
			get
			{
				return this.GetTable<usuario>();
			}
		}
		
		public System.Data.Linq.Table<compras> compras
		{
			get
			{
				return this.GetTable<compras>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ingreso_album_venta")]
		public int ingreso_album_venta([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Image")] System.Data.Linq.Binary portada, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> album_artista_id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Decimal(5,2)")] System.Nullable<decimal> precio, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> cantidad, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> album_disquera_id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nombre, portada, album_artista_id, precio, cantidad, album_disquera_id);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ingreso_artista")]
		public int ingreso_artista([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string nombre_artistico)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nombre_artistico);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ingreso_artista_cancion")]
		public int ingreso_artista_cancion([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> artista_id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> cancion_id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), artista_id, cancion_id);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ingreso_cancion")]
		public int ingreso_cancion([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string duracion, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Image")] System.Data.Linq.Binary imagen, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> numero_reproducciones, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> cancion_genero_musical_id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nombre, duracion, imagen, numero_reproducciones, cancion_genero_musical_id);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ingreso_disquera")]
		public int ingreso_disquera([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string nombre)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nombre);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ingreso_cancion_album")]
		public int ingreso_cancion_album([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> cancion_id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> album_id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cancion_id, album_id);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ingreso_factura")]
		public int ingreso_factura([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> fecha, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> usuario_id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> tienda_id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Decimal(5,2)")] System.Nullable<decimal> precio_final)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), fecha, usuario_id, tienda_id, precio_final);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ingreso_genero_musical")]
		public int ingreso_genero_musical([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string nombre)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nombre);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ingreso_item_factura")]
		public int ingreso_item_factura([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> factura_id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> album_id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> cantidad, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Decimal(5,2)")] System.Nullable<decimal> precio_item)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), factura_id, album_id, cantidad, precio_item);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ingreso_rol")]
		public int ingreso_rol([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(30)")] string tipo)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), tipo);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ingreso_persona")]
		public int ingreso_persona([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(30)")] string nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(30)")] string apellido, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> edad, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string celular)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nombre, apellido, edad, celular);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ingreso_tienda")]
		public int ingreso_tienda([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string direccion, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string ruc, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string telefono)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nombre, direccion, ruc, telefono);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ingreso_usuario")]
		public int ingreso_usuario([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(30)")] string nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string contrasenia, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(30)")] string correo, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> usuario_rol, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> persona_id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nombre, contrasenia, correo, usuario_rol, persona_id);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ingreso_compras")]
		public int ingreso_compras([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id_persona, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id_album)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id_persona, id_album);
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.album_venta")]
	public partial class album_venta : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _nombre;
		
		private System.Data.Linq.Binary _portada;
		
		private int _album_artista_id;
		
		private decimal _precio;
		
		private int _cantidad;
		
		private int _album_disquera_id;
		
		private System.Nullable<int> _calificacion;
		
		private EntitySet<cancion_album> _cancion_album;
		
		private EntitySet<item_factura> _item_factura;
		
		private EntitySet<compras> _compras;
		
		private EntityRef<artista> _artista;
		
		private EntityRef<disquera> _disquera;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    partial void OnportadaChanging(System.Data.Linq.Binary value);
    partial void OnportadaChanged();
    partial void Onalbum_artista_idChanging(int value);
    partial void Onalbum_artista_idChanged();
    partial void OnprecioChanging(decimal value);
    partial void OnprecioChanged();
    partial void OncantidadChanging(int value);
    partial void OncantidadChanged();
    partial void Onalbum_disquera_idChanging(int value);
    partial void Onalbum_disquera_idChanged();
    partial void OncalificacionChanging(System.Nullable<int> value);
    partial void OncalificacionChanged();
    #endregion
		
		public album_venta()
		{
			this._cancion_album = new EntitySet<cancion_album>(new Action<cancion_album>(this.attach_cancion_album), new Action<cancion_album>(this.detach_cancion_album));
			this._item_factura = new EntitySet<item_factura>(new Action<item_factura>(this.attach_item_factura), new Action<item_factura>(this.detach_item_factura));
			this._compras = new EntitySet<compras>(new Action<compras>(this.attach_compras), new Action<compras>(this.detach_compras));
			this._artista = default(EntityRef<artista>);
			this._disquera = default(EntityRef<disquera>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this.OnnombreChanging(value);
					this.SendPropertyChanging();
					this._nombre = value;
					this.SendPropertyChanged("nombre");
					this.OnnombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_portada", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary portada
		{
			get
			{
				return this._portada;
			}
			set
			{
				if ((this._portada != value))
				{
					this.OnportadaChanging(value);
					this.SendPropertyChanging();
					this._portada = value;
					this.SendPropertyChanged("portada");
					this.OnportadaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_album_artista_id", DbType="Int NOT NULL")]
		public int album_artista_id
		{
			get
			{
				return this._album_artista_id;
			}
			set
			{
				if ((this._album_artista_id != value))
				{
					if (this._artista.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onalbum_artista_idChanging(value);
					this.SendPropertyChanging();
					this._album_artista_id = value;
					this.SendPropertyChanged("album_artista_id");
					this.Onalbum_artista_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_precio", DbType="Decimal(5,2) NOT NULL")]
		public decimal precio
		{
			get
			{
				return this._precio;
			}
			set
			{
				if ((this._precio != value))
				{
					this.OnprecioChanging(value);
					this.SendPropertyChanging();
					this._precio = value;
					this.SendPropertyChanged("precio");
					this.OnprecioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cantidad", DbType="Int NOT NULL")]
		public int cantidad
		{
			get
			{
				return this._cantidad;
			}
			set
			{
				if ((this._cantidad != value))
				{
					this.OncantidadChanging(value);
					this.SendPropertyChanging();
					this._cantidad = value;
					this.SendPropertyChanged("cantidad");
					this.OncantidadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_album_disquera_id", DbType="Int NOT NULL")]
		public int album_disquera_id
		{
			get
			{
				return this._album_disquera_id;
			}
			set
			{
				if ((this._album_disquera_id != value))
				{
					if (this._disquera.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onalbum_disquera_idChanging(value);
					this.SendPropertyChanging();
					this._album_disquera_id = value;
					this.SendPropertyChanged("album_disquera_id");
					this.Onalbum_disquera_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_calificacion", DbType="Int")]
		public System.Nullable<int> calificacion
		{
			get
			{
				return this._calificacion;
			}
			set
			{
				if ((this._calificacion != value))
				{
					this.OncalificacionChanging(value);
					this.SendPropertyChanging();
					this._calificacion = value;
					this.SendPropertyChanged("calificacion");
					this.OncalificacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="album_venta_cancion_album", Storage="_cancion_album", ThisKey="id", OtherKey="album_id")]
		public EntitySet<cancion_album> cancion_album
		{
			get
			{
				return this._cancion_album;
			}
			set
			{
				this._cancion_album.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="album_venta_item_factura", Storage="_item_factura", ThisKey="id", OtherKey="album_id")]
		public EntitySet<item_factura> item_factura
		{
			get
			{
				return this._item_factura;
			}
			set
			{
				this._item_factura.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="album_venta_compras", Storage="_compras", ThisKey="id", OtherKey="album_id")]
		public EntitySet<compras> compras
		{
			get
			{
				return this._compras;
			}
			set
			{
				this._compras.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="artista_album_venta", Storage="_artista", ThisKey="album_artista_id", OtherKey="id", IsForeignKey=true)]
		public artista artista
		{
			get
			{
				return this._artista.Entity;
			}
			set
			{
				artista previousValue = this._artista.Entity;
				if (((previousValue != value) 
							|| (this._artista.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._artista.Entity = null;
						previousValue.album_venta.Remove(this);
					}
					this._artista.Entity = value;
					if ((value != null))
					{
						value.album_venta.Add(this);
						this._album_artista_id = value.id;
					}
					else
					{
						this._album_artista_id = default(int);
					}
					this.SendPropertyChanged("artista");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="disquera_album_venta", Storage="_disquera", ThisKey="album_disquera_id", OtherKey="id_disquera", IsForeignKey=true)]
		public disquera disquera
		{
			get
			{
				return this._disquera.Entity;
			}
			set
			{
				disquera previousValue = this._disquera.Entity;
				if (((previousValue != value) 
							|| (this._disquera.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._disquera.Entity = null;
						previousValue.album_venta.Remove(this);
					}
					this._disquera.Entity = value;
					if ((value != null))
					{
						value.album_venta.Add(this);
						this._album_disquera_id = value.id_disquera;
					}
					else
					{
						this._album_disquera_id = default(int);
					}
					this.SendPropertyChanged("disquera");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_cancion_album(cancion_album entity)
		{
			this.SendPropertyChanging();
			entity.album_venta = this;
		}
		
		private void detach_cancion_album(cancion_album entity)
		{
			this.SendPropertyChanging();
			entity.album_venta = null;
		}
		
		private void attach_item_factura(item_factura entity)
		{
			this.SendPropertyChanging();
			entity.album_venta = this;
		}
		
		private void detach_item_factura(item_factura entity)
		{
			this.SendPropertyChanging();
			entity.album_venta = null;
		}
		
		private void attach_compras(compras entity)
		{
			this.SendPropertyChanging();
			entity.album_venta = this;
		}
		
		private void detach_compras(compras entity)
		{
			this.SendPropertyChanging();
			entity.album_venta = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.artista")]
	public partial class artista : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _nombre_artistico;
		
		private EntitySet<album_venta> _album_venta;
		
		private EntitySet<artista_cancion> _artista_cancion;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Onnombre_artisticoChanging(string value);
    partial void Onnombre_artisticoChanged();
    #endregion
		
		public artista()
		{
			this._album_venta = new EntitySet<album_venta>(new Action<album_venta>(this.attach_album_venta), new Action<album_venta>(this.detach_album_venta));
			this._artista_cancion = new EntitySet<artista_cancion>(new Action<artista_cancion>(this.attach_artista_cancion), new Action<artista_cancion>(this.detach_artista_cancion));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre_artistico", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string nombre_artistico
		{
			get
			{
				return this._nombre_artistico;
			}
			set
			{
				if ((this._nombre_artistico != value))
				{
					this.Onnombre_artisticoChanging(value);
					this.SendPropertyChanging();
					this._nombre_artistico = value;
					this.SendPropertyChanged("nombre_artistico");
					this.Onnombre_artisticoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="artista_album_venta", Storage="_album_venta", ThisKey="id", OtherKey="album_artista_id")]
		public EntitySet<album_venta> album_venta
		{
			get
			{
				return this._album_venta;
			}
			set
			{
				this._album_venta.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="artista_artista_cancion", Storage="_artista_cancion", ThisKey="id", OtherKey="artista_id")]
		public EntitySet<artista_cancion> artista_cancion
		{
			get
			{
				return this._artista_cancion;
			}
			set
			{
				this._artista_cancion.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_album_venta(album_venta entity)
		{
			this.SendPropertyChanging();
			entity.artista = this;
		}
		
		private void detach_album_venta(album_venta entity)
		{
			this.SendPropertyChanging();
			entity.artista = null;
		}
		
		private void attach_artista_cancion(artista_cancion entity)
		{
			this.SendPropertyChanging();
			entity.artista = this;
		}
		
		private void detach_artista_cancion(artista_cancion entity)
		{
			this.SendPropertyChanging();
			entity.artista = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.artista_cancion")]
	public partial class artista_cancion : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private int _artista_id;
		
		private int _cancion_id;
		
		private EntityRef<artista> _artista;
		
		private EntityRef<cancion> _cancion;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Onartista_idChanging(int value);
    partial void Onartista_idChanged();
    partial void Oncancion_idChanging(int value);
    partial void Oncancion_idChanged();
    #endregion
		
		public artista_cancion()
		{
			this._artista = default(EntityRef<artista>);
			this._cancion = default(EntityRef<cancion>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_artista_id", DbType="Int NOT NULL")]
		public int artista_id
		{
			get
			{
				return this._artista_id;
			}
			set
			{
				if ((this._artista_id != value))
				{
					if (this._artista.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onartista_idChanging(value);
					this.SendPropertyChanging();
					this._artista_id = value;
					this.SendPropertyChanged("artista_id");
					this.Onartista_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cancion_id", DbType="Int NOT NULL")]
		public int cancion_id
		{
			get
			{
				return this._cancion_id;
			}
			set
			{
				if ((this._cancion_id != value))
				{
					if (this._cancion.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Oncancion_idChanging(value);
					this.SendPropertyChanging();
					this._cancion_id = value;
					this.SendPropertyChanged("cancion_id");
					this.Oncancion_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="artista_artista_cancion", Storage="_artista", ThisKey="artista_id", OtherKey="id", IsForeignKey=true)]
		public artista artista
		{
			get
			{
				return this._artista.Entity;
			}
			set
			{
				artista previousValue = this._artista.Entity;
				if (((previousValue != value) 
							|| (this._artista.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._artista.Entity = null;
						previousValue.artista_cancion.Remove(this);
					}
					this._artista.Entity = value;
					if ((value != null))
					{
						value.artista_cancion.Add(this);
						this._artista_id = value.id;
					}
					else
					{
						this._artista_id = default(int);
					}
					this.SendPropertyChanged("artista");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="cancion_artista_cancion", Storage="_cancion", ThisKey="cancion_id", OtherKey="id_cancion", IsForeignKey=true)]
		public cancion cancion
		{
			get
			{
				return this._cancion.Entity;
			}
			set
			{
				cancion previousValue = this._cancion.Entity;
				if (((previousValue != value) 
							|| (this._cancion.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._cancion.Entity = null;
						previousValue.artista_cancion.Remove(this);
					}
					this._cancion.Entity = value;
					if ((value != null))
					{
						value.artista_cancion.Add(this);
						this._cancion_id = value.id_cancion;
					}
					else
					{
						this._cancion_id = default(int);
					}
					this.SendPropertyChanged("cancion");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.cancion")]
	public partial class cancion : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_cancion;
		
		private string _nombre;
		
		private string _duracion;
		
		private System.Data.Linq.Binary _imagen;
		
		private System.Nullable<int> _numero_reproducciones;
		
		private int _cancion_genero_musical_id;
		
		private EntitySet<artista_cancion> _artista_cancion;
		
		private EntitySet<cancion_album> _cancion_album;
		
		private EntityRef<genero_musical> _genero_musical;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_cancionChanging(int value);
    partial void Onid_cancionChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    partial void OnduracionChanging(string value);
    partial void OnduracionChanged();
    partial void OnimagenChanging(System.Data.Linq.Binary value);
    partial void OnimagenChanged();
    partial void Onnumero_reproduccionesChanging(System.Nullable<int> value);
    partial void Onnumero_reproduccionesChanged();
    partial void Oncancion_genero_musical_idChanging(int value);
    partial void Oncancion_genero_musical_idChanged();
    #endregion
		
		public cancion()
		{
			this._artista_cancion = new EntitySet<artista_cancion>(new Action<artista_cancion>(this.attach_artista_cancion), new Action<artista_cancion>(this.detach_artista_cancion));
			this._cancion_album = new EntitySet<cancion_album>(new Action<cancion_album>(this.attach_cancion_album), new Action<cancion_album>(this.detach_cancion_album));
			this._genero_musical = default(EntityRef<genero_musical>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_cancion", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_cancion
		{
			get
			{
				return this._id_cancion;
			}
			set
			{
				if ((this._id_cancion != value))
				{
					this.Onid_cancionChanging(value);
					this.SendPropertyChanging();
					this._id_cancion = value;
					this.SendPropertyChanged("id_cancion");
					this.Onid_cancionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this.OnnombreChanging(value);
					this.SendPropertyChanging();
					this._nombre = value;
					this.SendPropertyChanged("nombre");
					this.OnnombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_duracion", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string duracion
		{
			get
			{
				return this._duracion;
			}
			set
			{
				if ((this._duracion != value))
				{
					this.OnduracionChanging(value);
					this.SendPropertyChanging();
					this._duracion = value;
					this.SendPropertyChanged("duracion");
					this.OnduracionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_imagen", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary imagen
		{
			get
			{
				return this._imagen;
			}
			set
			{
				if ((this._imagen != value))
				{
					this.OnimagenChanging(value);
					this.SendPropertyChanging();
					this._imagen = value;
					this.SendPropertyChanged("imagen");
					this.OnimagenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numero_reproducciones", DbType="Int")]
		public System.Nullable<int> numero_reproducciones
		{
			get
			{
				return this._numero_reproducciones;
			}
			set
			{
				if ((this._numero_reproducciones != value))
				{
					this.Onnumero_reproduccionesChanging(value);
					this.SendPropertyChanging();
					this._numero_reproducciones = value;
					this.SendPropertyChanged("numero_reproducciones");
					this.Onnumero_reproduccionesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cancion_genero_musical_id", DbType="Int NOT NULL")]
		public int cancion_genero_musical_id
		{
			get
			{
				return this._cancion_genero_musical_id;
			}
			set
			{
				if ((this._cancion_genero_musical_id != value))
				{
					if (this._genero_musical.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Oncancion_genero_musical_idChanging(value);
					this.SendPropertyChanging();
					this._cancion_genero_musical_id = value;
					this.SendPropertyChanged("cancion_genero_musical_id");
					this.Oncancion_genero_musical_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="cancion_artista_cancion", Storage="_artista_cancion", ThisKey="id_cancion", OtherKey="cancion_id")]
		public EntitySet<artista_cancion> artista_cancion
		{
			get
			{
				return this._artista_cancion;
			}
			set
			{
				this._artista_cancion.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="cancion_cancion_album", Storage="_cancion_album", ThisKey="id_cancion", OtherKey="cancion_id")]
		public EntitySet<cancion_album> cancion_album
		{
			get
			{
				return this._cancion_album;
			}
			set
			{
				this._cancion_album.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="genero_musical_cancion", Storage="_genero_musical", ThisKey="cancion_genero_musical_id", OtherKey="id", IsForeignKey=true)]
		public genero_musical genero_musical
		{
			get
			{
				return this._genero_musical.Entity;
			}
			set
			{
				genero_musical previousValue = this._genero_musical.Entity;
				if (((previousValue != value) 
							|| (this._genero_musical.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._genero_musical.Entity = null;
						previousValue.cancion.Remove(this);
					}
					this._genero_musical.Entity = value;
					if ((value != null))
					{
						value.cancion.Add(this);
						this._cancion_genero_musical_id = value.id;
					}
					else
					{
						this._cancion_genero_musical_id = default(int);
					}
					this.SendPropertyChanged("genero_musical");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_artista_cancion(artista_cancion entity)
		{
			this.SendPropertyChanging();
			entity.cancion = this;
		}
		
		private void detach_artista_cancion(artista_cancion entity)
		{
			this.SendPropertyChanging();
			entity.cancion = null;
		}
		
		private void attach_cancion_album(cancion_album entity)
		{
			this.SendPropertyChanging();
			entity.cancion = this;
		}
		
		private void detach_cancion_album(cancion_album entity)
		{
			this.SendPropertyChanging();
			entity.cancion = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.cancion_album")]
	public partial class cancion_album : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private int _cancion_id;
		
		private int _album_id;
		
		private EntityRef<album_venta> _album_venta;
		
		private EntityRef<cancion> _cancion;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Oncancion_idChanging(int value);
    partial void Oncancion_idChanged();
    partial void Onalbum_idChanging(int value);
    partial void Onalbum_idChanged();
    #endregion
		
		public cancion_album()
		{
			this._album_venta = default(EntityRef<album_venta>);
			this._cancion = default(EntityRef<cancion>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cancion_id", DbType="Int NOT NULL")]
		public int cancion_id
		{
			get
			{
				return this._cancion_id;
			}
			set
			{
				if ((this._cancion_id != value))
				{
					if (this._cancion.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Oncancion_idChanging(value);
					this.SendPropertyChanging();
					this._cancion_id = value;
					this.SendPropertyChanged("cancion_id");
					this.Oncancion_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_album_id", DbType="Int NOT NULL")]
		public int album_id
		{
			get
			{
				return this._album_id;
			}
			set
			{
				if ((this._album_id != value))
				{
					if (this._album_venta.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onalbum_idChanging(value);
					this.SendPropertyChanging();
					this._album_id = value;
					this.SendPropertyChanged("album_id");
					this.Onalbum_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="album_venta_cancion_album", Storage="_album_venta", ThisKey="album_id", OtherKey="id", IsForeignKey=true)]
		public album_venta album_venta
		{
			get
			{
				return this._album_venta.Entity;
			}
			set
			{
				album_venta previousValue = this._album_venta.Entity;
				if (((previousValue != value) 
							|| (this._album_venta.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._album_venta.Entity = null;
						previousValue.cancion_album.Remove(this);
					}
					this._album_venta.Entity = value;
					if ((value != null))
					{
						value.cancion_album.Add(this);
						this._album_id = value.id;
					}
					else
					{
						this._album_id = default(int);
					}
					this.SendPropertyChanged("album_venta");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="cancion_cancion_album", Storage="_cancion", ThisKey="cancion_id", OtherKey="id_cancion", IsForeignKey=true)]
		public cancion cancion
		{
			get
			{
				return this._cancion.Entity;
			}
			set
			{
				cancion previousValue = this._cancion.Entity;
				if (((previousValue != value) 
							|| (this._cancion.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._cancion.Entity = null;
						previousValue.cancion_album.Remove(this);
					}
					this._cancion.Entity = value;
					if ((value != null))
					{
						value.cancion_album.Add(this);
						this._cancion_id = value.id_cancion;
					}
					else
					{
						this._cancion_id = default(int);
					}
					this.SendPropertyChanged("cancion");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.disquera")]
	public partial class disquera : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_disquera;
		
		private string _nombre;
		
		private EntitySet<album_venta> _album_venta;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_disqueraChanging(int value);
    partial void Onid_disqueraChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    #endregion
		
		public disquera()
		{
			this._album_venta = new EntitySet<album_venta>(new Action<album_venta>(this.attach_album_venta), new Action<album_venta>(this.detach_album_venta));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_disquera", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_disquera
		{
			get
			{
				return this._id_disquera;
			}
			set
			{
				if ((this._id_disquera != value))
				{
					this.Onid_disqueraChanging(value);
					this.SendPropertyChanging();
					this._id_disquera = value;
					this.SendPropertyChanged("id_disquera");
					this.Onid_disqueraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this.OnnombreChanging(value);
					this.SendPropertyChanging();
					this._nombre = value;
					this.SendPropertyChanged("nombre");
					this.OnnombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="disquera_album_venta", Storage="_album_venta", ThisKey="id_disquera", OtherKey="album_disquera_id")]
		public EntitySet<album_venta> album_venta
		{
			get
			{
				return this._album_venta;
			}
			set
			{
				this._album_venta.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_album_venta(album_venta entity)
		{
			this.SendPropertyChanging();
			entity.disquera = this;
		}
		
		private void detach_album_venta(album_venta entity)
		{
			this.SendPropertyChanging();
			entity.disquera = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.factura")]
	public partial class factura : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_factura;
		
		private System.DateTime _fecha;
		
		private int _persona_id;
		
		private int _tienda_id;
		
		private System.Nullable<decimal> _precio_final;
		
		private EntitySet<item_factura> _item_factura;
		
		private EntityRef<persona> _persona;
		
		private EntityRef<tienda> _tienda;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_facturaChanging(int value);
    partial void Onid_facturaChanged();
    partial void OnfechaChanging(System.DateTime value);
    partial void OnfechaChanged();
    partial void Onpersona_idChanging(int value);
    partial void Onpersona_idChanged();
    partial void Ontienda_idChanging(int value);
    partial void Ontienda_idChanged();
    partial void Onprecio_finalChanging(System.Nullable<decimal> value);
    partial void Onprecio_finalChanged();
    #endregion
		
		public factura()
		{
			this._item_factura = new EntitySet<item_factura>(new Action<item_factura>(this.attach_item_factura), new Action<item_factura>(this.detach_item_factura));
			this._persona = default(EntityRef<persona>);
			this._tienda = default(EntityRef<tienda>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_factura", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_factura
		{
			get
			{
				return this._id_factura;
			}
			set
			{
				if ((this._id_factura != value))
				{
					this.Onid_facturaChanging(value);
					this.SendPropertyChanging();
					this._id_factura = value;
					this.SendPropertyChanged("id_factura");
					this.Onid_facturaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha", DbType="Date NOT NULL")]
		public System.DateTime fecha
		{
			get
			{
				return this._fecha;
			}
			set
			{
				if ((this._fecha != value))
				{
					this.OnfechaChanging(value);
					this.SendPropertyChanging();
					this._fecha = value;
					this.SendPropertyChanged("fecha");
					this.OnfechaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_persona_id", DbType="Int NOT NULL")]
		public int persona_id
		{
			get
			{
				return this._persona_id;
			}
			set
			{
				if ((this._persona_id != value))
				{
					if (this._persona.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onpersona_idChanging(value);
					this.SendPropertyChanging();
					this._persona_id = value;
					this.SendPropertyChanged("persona_id");
					this.Onpersona_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tienda_id", DbType="Int NOT NULL")]
		public int tienda_id
		{
			get
			{
				return this._tienda_id;
			}
			set
			{
				if ((this._tienda_id != value))
				{
					if (this._tienda.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Ontienda_idChanging(value);
					this.SendPropertyChanging();
					this._tienda_id = value;
					this.SendPropertyChanged("tienda_id");
					this.Ontienda_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_precio_final", DbType="Decimal(5,2)")]
		public System.Nullable<decimal> precio_final
		{
			get
			{
				return this._precio_final;
			}
			set
			{
				if ((this._precio_final != value))
				{
					this.Onprecio_finalChanging(value);
					this.SendPropertyChanging();
					this._precio_final = value;
					this.SendPropertyChanged("precio_final");
					this.Onprecio_finalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="factura_item_factura", Storage="_item_factura", ThisKey="id_factura", OtherKey="factura_id")]
		public EntitySet<item_factura> item_factura
		{
			get
			{
				return this._item_factura;
			}
			set
			{
				this._item_factura.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="persona_factura", Storage="_persona", ThisKey="persona_id", OtherKey="id_persona", IsForeignKey=true)]
		public persona persona
		{
			get
			{
				return this._persona.Entity;
			}
			set
			{
				persona previousValue = this._persona.Entity;
				if (((previousValue != value) 
							|| (this._persona.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._persona.Entity = null;
						previousValue.factura.Remove(this);
					}
					this._persona.Entity = value;
					if ((value != null))
					{
						value.factura.Add(this);
						this._persona_id = value.id_persona;
					}
					else
					{
						this._persona_id = default(int);
					}
					this.SendPropertyChanged("persona");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tienda_factura", Storage="_tienda", ThisKey="tienda_id", OtherKey="id_tienda", IsForeignKey=true)]
		public tienda tienda
		{
			get
			{
				return this._tienda.Entity;
			}
			set
			{
				tienda previousValue = this._tienda.Entity;
				if (((previousValue != value) 
							|| (this._tienda.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tienda.Entity = null;
						previousValue.factura.Remove(this);
					}
					this._tienda.Entity = value;
					if ((value != null))
					{
						value.factura.Add(this);
						this._tienda_id = value.id_tienda;
					}
					else
					{
						this._tienda_id = default(int);
					}
					this.SendPropertyChanged("tienda");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_item_factura(item_factura entity)
		{
			this.SendPropertyChanging();
			entity.factura = this;
		}
		
		private void detach_item_factura(item_factura entity)
		{
			this.SendPropertyChanging();
			entity.factura = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.genero_musical")]
	public partial class genero_musical : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _nombre;
		
		private EntitySet<cancion> _cancion;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    #endregion
		
		public genero_musical()
		{
			this._cancion = new EntitySet<cancion>(new Action<cancion>(this.attach_cancion), new Action<cancion>(this.detach_cancion));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this.OnnombreChanging(value);
					this.SendPropertyChanging();
					this._nombre = value;
					this.SendPropertyChanged("nombre");
					this.OnnombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="genero_musical_cancion", Storage="_cancion", ThisKey="id", OtherKey="cancion_genero_musical_id")]
		public EntitySet<cancion> cancion
		{
			get
			{
				return this._cancion;
			}
			set
			{
				this._cancion.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_cancion(cancion entity)
		{
			this.SendPropertyChanging();
			entity.genero_musical = this;
		}
		
		private void detach_cancion(cancion entity)
		{
			this.SendPropertyChanging();
			entity.genero_musical = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.item_factura")]
	public partial class item_factura : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_item;
		
		private int _factura_id;
		
		private int _album_id;
		
		private int _cantidad;
		
		private System.Nullable<decimal> _precio_item;
		
		private EntityRef<album_venta> _album_venta;
		
		private EntityRef<factura> _factura;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_itemChanging(int value);
    partial void Onid_itemChanged();
    partial void Onfactura_idChanging(int value);
    partial void Onfactura_idChanged();
    partial void Onalbum_idChanging(int value);
    partial void Onalbum_idChanged();
    partial void OncantidadChanging(int value);
    partial void OncantidadChanged();
    partial void Onprecio_itemChanging(System.Nullable<decimal> value);
    partial void Onprecio_itemChanged();
    #endregion
		
		public item_factura()
		{
			this._album_venta = default(EntityRef<album_venta>);
			this._factura = default(EntityRef<factura>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_item", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_item
		{
			get
			{
				return this._id_item;
			}
			set
			{
				if ((this._id_item != value))
				{
					this.Onid_itemChanging(value);
					this.SendPropertyChanging();
					this._id_item = value;
					this.SendPropertyChanged("id_item");
					this.Onid_itemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_factura_id", DbType="Int NOT NULL")]
		public int factura_id
		{
			get
			{
				return this._factura_id;
			}
			set
			{
				if ((this._factura_id != value))
				{
					if (this._factura.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onfactura_idChanging(value);
					this.SendPropertyChanging();
					this._factura_id = value;
					this.SendPropertyChanged("factura_id");
					this.Onfactura_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_album_id", DbType="Int NOT NULL")]
		public int album_id
		{
			get
			{
				return this._album_id;
			}
			set
			{
				if ((this._album_id != value))
				{
					if (this._album_venta.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onalbum_idChanging(value);
					this.SendPropertyChanging();
					this._album_id = value;
					this.SendPropertyChanged("album_id");
					this.Onalbum_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cantidad", DbType="Int NOT NULL")]
		public int cantidad
		{
			get
			{
				return this._cantidad;
			}
			set
			{
				if ((this._cantidad != value))
				{
					this.OncantidadChanging(value);
					this.SendPropertyChanging();
					this._cantidad = value;
					this.SendPropertyChanged("cantidad");
					this.OncantidadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_precio_item", DbType="Decimal(5,2)")]
		public System.Nullable<decimal> precio_item
		{
			get
			{
				return this._precio_item;
			}
			set
			{
				if ((this._precio_item != value))
				{
					this.Onprecio_itemChanging(value);
					this.SendPropertyChanging();
					this._precio_item = value;
					this.SendPropertyChanged("precio_item");
					this.Onprecio_itemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="album_venta_item_factura", Storage="_album_venta", ThisKey="album_id", OtherKey="id", IsForeignKey=true)]
		public album_venta album_venta
		{
			get
			{
				return this._album_venta.Entity;
			}
			set
			{
				album_venta previousValue = this._album_venta.Entity;
				if (((previousValue != value) 
							|| (this._album_venta.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._album_venta.Entity = null;
						previousValue.item_factura.Remove(this);
					}
					this._album_venta.Entity = value;
					if ((value != null))
					{
						value.item_factura.Add(this);
						this._album_id = value.id;
					}
					else
					{
						this._album_id = default(int);
					}
					this.SendPropertyChanged("album_venta");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="factura_item_factura", Storage="_factura", ThisKey="factura_id", OtherKey="id_factura", IsForeignKey=true)]
		public factura factura
		{
			get
			{
				return this._factura.Entity;
			}
			set
			{
				factura previousValue = this._factura.Entity;
				if (((previousValue != value) 
							|| (this._factura.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._factura.Entity = null;
						previousValue.item_factura.Remove(this);
					}
					this._factura.Entity = value;
					if ((value != null))
					{
						value.item_factura.Add(this);
						this._factura_id = value.id_factura;
					}
					else
					{
						this._factura_id = default(int);
					}
					this.SendPropertyChanged("factura");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.persona")]
	public partial class persona : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_persona;
		
		private string _nombre;
		
		private string _apellido;
		
		private System.Nullable<int> _edad;
		
		private string _celular;
		
		private EntitySet<factura> _factura;
		
		private EntitySet<usuario> _usuario;
		
		private EntitySet<compras> _compras;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_personaChanging(int value);
    partial void Onid_personaChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    partial void OnapellidoChanging(string value);
    partial void OnapellidoChanged();
    partial void OnedadChanging(System.Nullable<int> value);
    partial void OnedadChanged();
    partial void OncelularChanging(string value);
    partial void OncelularChanged();
    #endregion
		
		public persona()
		{
			this._factura = new EntitySet<factura>(new Action<factura>(this.attach_factura), new Action<factura>(this.detach_factura));
			this._usuario = new EntitySet<usuario>(new Action<usuario>(this.attach_usuario), new Action<usuario>(this.detach_usuario));
			this._compras = new EntitySet<compras>(new Action<compras>(this.attach_compras), new Action<compras>(this.detach_compras));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_persona", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_persona
		{
			get
			{
				return this._id_persona;
			}
			set
			{
				if ((this._id_persona != value))
				{
					this.Onid_personaChanging(value);
					this.SendPropertyChanging();
					this._id_persona = value;
					this.SendPropertyChanged("id_persona");
					this.Onid_personaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this.OnnombreChanging(value);
					this.SendPropertyChanging();
					this._nombre = value;
					this.SendPropertyChanged("nombre");
					this.OnnombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_apellido", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string apellido
		{
			get
			{
				return this._apellido;
			}
			set
			{
				if ((this._apellido != value))
				{
					this.OnapellidoChanging(value);
					this.SendPropertyChanging();
					this._apellido = value;
					this.SendPropertyChanged("apellido");
					this.OnapellidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_edad", DbType="Int")]
		public System.Nullable<int> edad
		{
			get
			{
				return this._edad;
			}
			set
			{
				if ((this._edad != value))
				{
					this.OnedadChanging(value);
					this.SendPropertyChanging();
					this._edad = value;
					this.SendPropertyChanged("edad");
					this.OnedadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_celular", DbType="VarChar(10)")]
		public string celular
		{
			get
			{
				return this._celular;
			}
			set
			{
				if ((this._celular != value))
				{
					this.OncelularChanging(value);
					this.SendPropertyChanging();
					this._celular = value;
					this.SendPropertyChanged("celular");
					this.OncelularChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="persona_factura", Storage="_factura", ThisKey="id_persona", OtherKey="persona_id")]
		public EntitySet<factura> factura
		{
			get
			{
				return this._factura;
			}
			set
			{
				this._factura.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="persona_usuario", Storage="_usuario", ThisKey="id_persona", OtherKey="usuario_persona_id")]
		public EntitySet<usuario> usuario
		{
			get
			{
				return this._usuario;
			}
			set
			{
				this._usuario.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="persona_compras", Storage="_compras", ThisKey="id_persona", OtherKey="persona_id")]
		public EntitySet<compras> compras
		{
			get
			{
				return this._compras;
			}
			set
			{
				this._compras.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_factura(factura entity)
		{
			this.SendPropertyChanging();
			entity.persona = this;
		}
		
		private void detach_factura(factura entity)
		{
			this.SendPropertyChanging();
			entity.persona = null;
		}
		
		private void attach_usuario(usuario entity)
		{
			this.SendPropertyChanging();
			entity.persona = this;
		}
		
		private void detach_usuario(usuario entity)
		{
			this.SendPropertyChanging();
			entity.persona = null;
		}
		
		private void attach_compras(compras entity)
		{
			this.SendPropertyChanging();
			entity.persona = this;
		}
		
		private void detach_compras(compras entity)
		{
			this.SendPropertyChanging();
			entity.persona = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.rol")]
	public partial class rol : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_rol;
		
		private string _tipo;
		
		private EntitySet<usuario> _usuario;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_rolChanging(int value);
    partial void Onid_rolChanged();
    partial void OntipoChanging(string value);
    partial void OntipoChanged();
    #endregion
		
		public rol()
		{
			this._usuario = new EntitySet<usuario>(new Action<usuario>(this.attach_usuario), new Action<usuario>(this.detach_usuario));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_rol", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_rol
		{
			get
			{
				return this._id_rol;
			}
			set
			{
				if ((this._id_rol != value))
				{
					this.Onid_rolChanging(value);
					this.SendPropertyChanging();
					this._id_rol = value;
					this.SendPropertyChanged("id_rol");
					this.Onid_rolChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tipo", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string tipo
		{
			get
			{
				return this._tipo;
			}
			set
			{
				if ((this._tipo != value))
				{
					this.OntipoChanging(value);
					this.SendPropertyChanging();
					this._tipo = value;
					this.SendPropertyChanged("tipo");
					this.OntipoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="rol_usuario", Storage="_usuario", ThisKey="id_rol", OtherKey="usuario_rol_id")]
		public EntitySet<usuario> usuario
		{
			get
			{
				return this._usuario;
			}
			set
			{
				this._usuario.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_usuario(usuario entity)
		{
			this.SendPropertyChanging();
			entity.rol = this;
		}
		
		private void detach_usuario(usuario entity)
		{
			this.SendPropertyChanging();
			entity.rol = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tienda")]
	public partial class tienda : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_tienda;
		
		private string _nombre_tienda;
		
		private string _direccion_tienda;
		
		private string _ruc;
		
		private string _telefono;
		
		private EntitySet<factura> _factura;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_tiendaChanging(int value);
    partial void Onid_tiendaChanged();
    partial void Onnombre_tiendaChanging(string value);
    partial void Onnombre_tiendaChanged();
    partial void Ondireccion_tiendaChanging(string value);
    partial void Ondireccion_tiendaChanged();
    partial void OnrucChanging(string value);
    partial void OnrucChanged();
    partial void OntelefonoChanging(string value);
    partial void OntelefonoChanged();
    #endregion
		
		public tienda()
		{
			this._factura = new EntitySet<factura>(new Action<factura>(this.attach_factura), new Action<factura>(this.detach_factura));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_tienda", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_tienda
		{
			get
			{
				return this._id_tienda;
			}
			set
			{
				if ((this._id_tienda != value))
				{
					this.Onid_tiendaChanging(value);
					this.SendPropertyChanging();
					this._id_tienda = value;
					this.SendPropertyChanged("id_tienda");
					this.Onid_tiendaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre_tienda", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string nombre_tienda
		{
			get
			{
				return this._nombre_tienda;
			}
			set
			{
				if ((this._nombre_tienda != value))
				{
					this.Onnombre_tiendaChanging(value);
					this.SendPropertyChanging();
					this._nombre_tienda = value;
					this.SendPropertyChanged("nombre_tienda");
					this.Onnombre_tiendaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_direccion_tienda", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string direccion_tienda
		{
			get
			{
				return this._direccion_tienda;
			}
			set
			{
				if ((this._direccion_tienda != value))
				{
					this.Ondireccion_tiendaChanging(value);
					this.SendPropertyChanging();
					this._direccion_tienda = value;
					this.SendPropertyChanged("direccion_tienda");
					this.Ondireccion_tiendaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ruc", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string ruc
		{
			get
			{
				return this._ruc;
			}
			set
			{
				if ((this._ruc != value))
				{
					this.OnrucChanging(value);
					this.SendPropertyChanging();
					this._ruc = value;
					this.SendPropertyChanged("ruc");
					this.OnrucChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telefono", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string telefono
		{
			get
			{
				return this._telefono;
			}
			set
			{
				if ((this._telefono != value))
				{
					this.OntelefonoChanging(value);
					this.SendPropertyChanging();
					this._telefono = value;
					this.SendPropertyChanged("telefono");
					this.OntelefonoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tienda_factura", Storage="_factura", ThisKey="id_tienda", OtherKey="tienda_id")]
		public EntitySet<factura> factura
		{
			get
			{
				return this._factura;
			}
			set
			{
				this._factura.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_factura(factura entity)
		{
			this.SendPropertyChanging();
			entity.tienda = this;
		}
		
		private void detach_factura(factura entity)
		{
			this.SendPropertyChanging();
			entity.tienda = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.usuario")]
	public partial class usuario : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_usuario;
		
		private string _nombre_usuario;
		
		private string _contrasenia;
		
		private string _correo_electronico;
		
		private int _usuario_rol_id;
		
		private int _usuario_persona_id;
		
		private EntityRef<persona> _persona;
		
		private EntityRef<rol> _rol;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_usuarioChanging(int value);
    partial void Onid_usuarioChanged();
    partial void Onnombre_usuarioChanging(string value);
    partial void Onnombre_usuarioChanged();
    partial void OncontraseniaChanging(string value);
    partial void OncontraseniaChanged();
    partial void Oncorreo_electronicoChanging(string value);
    partial void Oncorreo_electronicoChanged();
    partial void Onusuario_rol_idChanging(int value);
    partial void Onusuario_rol_idChanged();
    partial void Onusuario_persona_idChanging(int value);
    partial void Onusuario_persona_idChanged();
    #endregion
		
		public usuario()
		{
			this._persona = default(EntityRef<persona>);
			this._rol = default(EntityRef<rol>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_usuario", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_usuario
		{
			get
			{
				return this._id_usuario;
			}
			set
			{
				if ((this._id_usuario != value))
				{
					this.Onid_usuarioChanging(value);
					this.SendPropertyChanging();
					this._id_usuario = value;
					this.SendPropertyChanged("id_usuario");
					this.Onid_usuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre_usuario", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string nombre_usuario
		{
			get
			{
				return this._nombre_usuario;
			}
			set
			{
				if ((this._nombre_usuario != value))
				{
					this.Onnombre_usuarioChanging(value);
					this.SendPropertyChanging();
					this._nombre_usuario = value;
					this.SendPropertyChanged("nombre_usuario");
					this.Onnombre_usuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_contrasenia", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string contrasenia
		{
			get
			{
				return this._contrasenia;
			}
			set
			{
				if ((this._contrasenia != value))
				{
					this.OncontraseniaChanging(value);
					this.SendPropertyChanging();
					this._contrasenia = value;
					this.SendPropertyChanged("contrasenia");
					this.OncontraseniaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_correo_electronico", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string correo_electronico
		{
			get
			{
				return this._correo_electronico;
			}
			set
			{
				if ((this._correo_electronico != value))
				{
					this.Oncorreo_electronicoChanging(value);
					this.SendPropertyChanging();
					this._correo_electronico = value;
					this.SendPropertyChanged("correo_electronico");
					this.Oncorreo_electronicoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usuario_rol_id", DbType="Int NOT NULL")]
		public int usuario_rol_id
		{
			get
			{
				return this._usuario_rol_id;
			}
			set
			{
				if ((this._usuario_rol_id != value))
				{
					if (this._rol.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onusuario_rol_idChanging(value);
					this.SendPropertyChanging();
					this._usuario_rol_id = value;
					this.SendPropertyChanged("usuario_rol_id");
					this.Onusuario_rol_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usuario_persona_id", DbType="Int NOT NULL")]
		public int usuario_persona_id
		{
			get
			{
				return this._usuario_persona_id;
			}
			set
			{
				if ((this._usuario_persona_id != value))
				{
					if (this._persona.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onusuario_persona_idChanging(value);
					this.SendPropertyChanging();
					this._usuario_persona_id = value;
					this.SendPropertyChanged("usuario_persona_id");
					this.Onusuario_persona_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="persona_usuario", Storage="_persona", ThisKey="usuario_persona_id", OtherKey="id_persona", IsForeignKey=true)]
		public persona persona
		{
			get
			{
				return this._persona.Entity;
			}
			set
			{
				persona previousValue = this._persona.Entity;
				if (((previousValue != value) 
							|| (this._persona.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._persona.Entity = null;
						previousValue.usuario.Remove(this);
					}
					this._persona.Entity = value;
					if ((value != null))
					{
						value.usuario.Add(this);
						this._usuario_persona_id = value.id_persona;
					}
					else
					{
						this._usuario_persona_id = default(int);
					}
					this.SendPropertyChanged("persona");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="rol_usuario", Storage="_rol", ThisKey="usuario_rol_id", OtherKey="id_rol", IsForeignKey=true)]
		public rol rol
		{
			get
			{
				return this._rol.Entity;
			}
			set
			{
				rol previousValue = this._rol.Entity;
				if (((previousValue != value) 
							|| (this._rol.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._rol.Entity = null;
						previousValue.usuario.Remove(this);
					}
					this._rol.Entity = value;
					if ((value != null))
					{
						value.usuario.Add(this);
						this._usuario_rol_id = value.id_rol;
					}
					else
					{
						this._usuario_rol_id = default(int);
					}
					this.SendPropertyChanged("rol");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.compras")]
	public partial class compras : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private int _persona_id;
		
		private int _album_id;
		
		private EntityRef<album_venta> _album_venta;
		
		private EntityRef<persona> _persona;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Onpersona_idChanging(int value);
    partial void Onpersona_idChanged();
    partial void Onalbum_idChanging(int value);
    partial void Onalbum_idChanged();
    #endregion
		
		public compras()
		{
			this._album_venta = default(EntityRef<album_venta>);
			this._persona = default(EntityRef<persona>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_persona_id", DbType="Int NOT NULL")]
		public int persona_id
		{
			get
			{
				return this._persona_id;
			}
			set
			{
				if ((this._persona_id != value))
				{
					if (this._persona.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onpersona_idChanging(value);
					this.SendPropertyChanging();
					this._persona_id = value;
					this.SendPropertyChanged("persona_id");
					this.Onpersona_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_album_id", DbType="Int NOT NULL")]
		public int album_id
		{
			get
			{
				return this._album_id;
			}
			set
			{
				if ((this._album_id != value))
				{
					if (this._album_venta.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onalbum_idChanging(value);
					this.SendPropertyChanging();
					this._album_id = value;
					this.SendPropertyChanged("album_id");
					this.Onalbum_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="album_venta_compras", Storage="_album_venta", ThisKey="album_id", OtherKey="id", IsForeignKey=true)]
		public album_venta album_venta
		{
			get
			{
				return this._album_venta.Entity;
			}
			set
			{
				album_venta previousValue = this._album_venta.Entity;
				if (((previousValue != value) 
							|| (this._album_venta.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._album_venta.Entity = null;
						previousValue.compras.Remove(this);
					}
					this._album_venta.Entity = value;
					if ((value != null))
					{
						value.compras.Add(this);
						this._album_id = value.id;
					}
					else
					{
						this._album_id = default(int);
					}
					this.SendPropertyChanged("album_venta");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="persona_compras", Storage="_persona", ThisKey="persona_id", OtherKey="id_persona", IsForeignKey=true)]
		public persona persona
		{
			get
			{
				return this._persona.Entity;
			}
			set
			{
				persona previousValue = this._persona.Entity;
				if (((previousValue != value) 
							|| (this._persona.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._persona.Entity = null;
						previousValue.compras.Remove(this);
					}
					this._persona.Entity = value;
					if ((value != null))
					{
						value.compras.Add(this);
						this._persona_id = value.id_persona;
					}
					else
					{
						this._persona_id = default(int);
					}
					this.SendPropertyChanged("persona");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
